spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:  
    driver-class-name: org.h2.Driver
    data: classpath:data-h2.sql
    sql-script-encoding: UTF-8