insert into category (name, category_id) values('노래', 1)
insert into category (name, category_id) values('영화', 2)
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/1_so_cool.png', '쏘쿨', 1 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/2_chorun.png', '초련', 2 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/3_americano.png', '아메리카노', 3 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/4_choolcheck.png', '출첵', 4 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/5_gajimagajima.png', '가지마가지마', 5 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/6_ikkit.png', '이 소설의 끝을 써보려해', 6 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/7_jani.png', '자니', 7 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/8_ringdingdong.png', '링딩동', 8 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/9_oppacar.png', '오빠차', 9 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/10_fantasticbaby.png', '판타스틱베이비', 10 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/11_tanjinjam.png', '고민보다 고', 11 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/12_lusiper.png', '루시퍼', 12 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/13_runtoyou.png', '런투유', 13 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/14_footfoot.png', '발걸음', 14 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (1 ,0, '/images/15_order.png', '주문', 15 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/16_lifeofpie.png', '라이프 오브 파이', 16 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/17_inception.png', '인셉션', 17 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/18_salin.png', '살인의 추억', 18 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/19_ring.png', '링', 19 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/20_jobs.png', '잡스', 20 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/21_ringofking.png', '반지의 제왕', 21 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/22_tor.png', '토르', 22 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/23_500dayssummer.png', '500일의 썸머', 23 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/24_home_alone.png', '나홀로 집에', 24 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/25_et.png', '이티', 25 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/26_ratatouille.png', '라따뚜이', 26 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/27_devil_wears_prada.png', '악마의 프라다를 입는다', 27 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/28_charlie.png', '찰리와 초콜릿 공장', 28 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/29_les.png', '레미제라블', 29 )
insert into quiz (category_id, delete, image_path, solution, quiz_id ) values (2 ,0, '/images/30_psycho.png', '싸이코', 30 )
insert into hint (message, quiz_id, hint_id) values ('아이돌', 1, 1)
insert into hint (message, quiz_id, hint_id) values ('걸그룹', 1, 2)
insert into hint (message, quiz_id, hint_id) values ('여름', 1, 3)
insert into hint (message, quiz_id, hint_id) values ('안무', 2, 4)
insert into hint (message, quiz_id, hint_id) values ('90년대 남성듀오', 2, 5)
insert into hint (message, quiz_id, hint_id) values ('DJ', 2, 6)
insert into hint (message, quiz_id, hint_id) values ('인디밴드', 3, 7)
insert into hint (message, quiz_id, hint_id) values ('노래제목', 3, 8)
insert into hint (message, quiz_id, hint_id) values ('커피', 3, 9)
insert into hint (message, quiz_id, hint_id) values ('힙합', 4, 10)
insert into hint (message, quiz_id, hint_id) values ('개코', 4, 11)
insert into hint (message, quiz_id, hint_id) values ('노래제목', 4, 12)
insert into hint (message, quiz_id, hint_id) values ('노래제목', 5, 13)
insert into hint (message, quiz_id, hint_id) values ('발라드', 5, 14)
insert into hint (message, quiz_id, hint_id) values ('나얼', 5, 15)
insert into hint (message, quiz_id, hint_id) values ('발라드', 6, 16)
insert into hint (message, quiz_id, hint_id) values ('노래제목', 6, 17)
insert into hint (message, quiz_id, hint_id) values ('한동근', 6, 18)
insert into hint (message, quiz_id, hint_id) values ('박스머리', 7, 19)
insert into hint (message, quiz_id, hint_id) values ('프로듀서', 7, 20)
insert into hint (message, quiz_id, hint_id) values ('다이나믹듀오', 7, 21)
insert into hint (message, quiz_id, hint_id) values ('아이돌', 8, 22)
insert into hint (message, quiz_id, hint_id) values ('보이그룹', 8, 23)
insert into hint (message, quiz_id, hint_id) values ('SM', 8, 24)
insert into hint (message, quiz_id, hint_id) values ('타블로', 9, 25)
insert into hint (message, quiz_id, hint_id) values ('슈퍼비', 9, 26)
insert into hint (message, quiz_id, hint_id) values ('쇼미더머니', 9, 27)
insert into hint (message, quiz_id, hint_id) values ('미역머리', 10, 28)
insert into hint (message, quiz_id, hint_id) values ('양싸', 10, 29)
insert into hint (message, quiz_id, hint_id) values ('YG', 10, 30)
insert into hint (message, quiz_id, hint_id) values ('YOLO', 11, 31)
insert into hint (message, quiz_id, hint_id) values ('오늘만산다', 11, 32)
insert into hint (message, quiz_id, hint_id) values ('월드스타', 11, 33)
insert into hint (message, quiz_id, hint_id) values ('보이그룹', 12, 34)
insert into hint (message, quiz_id, hint_id) values ('스키니진', 12, 35)
insert into hint (message, quiz_id, hint_id) values ('SM', 12, 36)
insert into hint (message, quiz_id, hint_id) values ('댄스', 13, 37)
insert into hint (message, quiz_id, hint_id) values ('3인조', 13, 38)
insert into hint (message, quiz_id, hint_id) values ('90년대', 13, 39)
insert into hint (message, quiz_id, hint_id) values ('90년대', 14, 40)
insert into hint (message, quiz_id, hint_id) values ('락밴드', 14, 41)
insert into hint (message, quiz_id, hint_id) values ('날위해', 14, 42)
insert into hint (message, quiz_id, hint_id) values ('보이그룹', 15, 43)
insert into hint (message, quiz_id, hint_id) values ('아이돌', 15, 44)
insert into hint (message, quiz_id, hint_id) values ('SM', 15, 45)
insert into hint (message, quiz_id, hint_id) values ('판타지', 16, 46)
insert into hint (message, quiz_id, hint_id) values ('표류', 16, 47)
insert into hint (message, quiz_id, hint_id) values ('인도', 16, 48)
insert into hint (message, quiz_id, hint_id) values ('팽이', 17, 49)
insert into hint (message, quiz_id, hint_id) values ('레오나르도디카프리오', 17, 50)
insert into hint (message, quiz_id, hint_id) values ('꿈', 17, 51)
insert into hint (message, quiz_id, hint_id) values ('송강호', 18, 52)
insert into hint (message, quiz_id, hint_id) values ('범죄', 18, 53)
insert into hint (message, quiz_id, hint_id) values ('화성', 18, 54)
insert into hint (message, quiz_id, hint_id) values ('판타지', 19, 55)
insert into hint (message, quiz_id, hint_id) values ('표류', 19, 56)
insert into hint (message, quiz_id, hint_id) values ('인도', 19, 57)
insert into hint (message, quiz_id, hint_id) values ('CEO', 20, 58)
insert into hint (message, quiz_id, hint_id) values ('애쉬튼커쳐', 20, 59)
insert into hint (message, quiz_id, hint_id) values ('애플', 20, 60)
insert into hint (message, quiz_id, hint_id) values ('판타지', 21, 61)
insert into hint (message, quiz_id, hint_id) values ('피터잭슨', 21, 62)
insert into hint (message, quiz_id, hint_id) values ('골룸', 21, 63)
insert into hint (message, quiz_id, hint_id) values ('어벤져스', 22, 64)
insert into hint (message, quiz_id, hint_id) values ('크리스 햄스위즈', 22, 65)
insert into hint (message, quiz_id, hint_id) values ('로키', 22, 66)
insert into hint (message, quiz_id, hint_id) values ('로맨스', 23, 67)
insert into hint (message, quiz_id, hint_id) values ('주이 디샤넬', 23, 68)
insert into hint (message, quiz_id, hint_id) values ('연애', 23, 69)
insert into hint (message, quiz_id, hint_id) values ('솔로', 24, 70)
insert into hint (message, quiz_id, hint_id) values ('크리스마스', 24, 71)
insert into hint (message, quiz_id, hint_id) values ('맥컬리컬킨', 24, 72)
insert into hint (message, quiz_id, hint_id) values ('갓띵작', 25, 73)
insert into hint (message, quiz_id, hint_id) values ('판타지', 25, 74)
insert into hint (message, quiz_id, hint_id) values ('스티븐스필버그', 25, 75)
insert into hint (message, quiz_id, hint_id) values ('요리', 26, 76)
insert into hint (message, quiz_id, hint_id) values ('애니메이션', 26, 77)
insert into hint (message, quiz_id, hint_id) values ('미국', 26, 78)
insert into hint (message, quiz_id, hint_id) values ('책원작', 27, 79)
insert into hint (message, quiz_id, hint_id) values ('패션계', 27, 80)
insert into hint (message, quiz_id, hint_id) values ('앤해서웨이', 27, 81)
insert into hint (message, quiz_id, hint_id) values ('판타지', 28, 82)
insert into hint (message, quiz_id, hint_id) values ('책원작', 28, 83)
insert into hint (message, quiz_id, hint_id) values ('팀버튼', 28, 84)
insert into hint (message, quiz_id, hint_id) values ('책원작', 29, 85)
insert into hint (message, quiz_id, hint_id) values ('앤해서웨이', 29, 86)
insert into hint (message, quiz_id, hint_id) values ('뮤지컬', 29, 87)
insert into hint (message, quiz_id, hint_id) values ('고전', 30, 88)
insert into hint (message, quiz_id, hint_id) values ('스릴러', 30, 89)
insert into hint (message, quiz_id, hint_id) values ('히치콕', 30, 90)
